# Dockerfile.server

FROM node:16.17.1-alpine3.16
WORKDIR /usr/app
COPY server/package*.json ./
RUN npm ci
COPY server/ ./
COPY --from=build /usr/app/dist ./client/dist
EXPOSE 4008
CMD ["node", "server.js"]
