services:
  - type: web
    name: bams-client
    runtime: docker
    repo: https://github.com/DiFrescoTisha-FS/bams.git
    branch: dev
    plan: standard
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: VITE_APP_ENV
        value: development
      - key: VITE_API_URL
        value: http://localhost:4008  # Placeholder, to be updated
      - key: VITE_GOOGLE_CLIENT_ID
        value: 630469049970-161iihf5mjh96rt6mj963asetm2cv665.apps.googleusercontent.com
      - key: VITE_CLOUDINARY_NAME
        value: djqw1de3s
      - key: VITE_BASE_URL
        value: http://localhost:4008  # Placeholder, to be updated
      - key: VITE_PORT
        value: 5173
    region: virginia

  - type: web
    name: bams-server
    runtime: docker
    repo: https://github.com/DiFrescoTisha-FS/bams.git
    branch: dev
    plan: standard
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 4008
      - key: MONGO_URI
        value: mongodb+srv://tishd7:MihiaBFL68@fullstack.hkhucia.mongodb.net/?retryWrites=true&w=majority&appName=fullstack
      - key: GOOGLE_CLIENT_ID
        value: 630469049970-vlu6fe64h4dh1ljqdqlo538g33tqmh6t.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: SESSION_SECRET
        value: xg5St2ygd+mCIrMOjSomZ77kPpGK+yaDmVvvHf+z2aw4smGrmoKi1QyaPzRvaaXYJh4cN5uGf9oebpTzhmgt1w==
      - key: REDIRECT_URL
        value: http://localhost:4008/auth/google/callback  # Placeholder, to be updated
      - key: BASE_URL
        value: http://localhost:4008  # Placeholder, to be updated
      - key: API_URL
        value: http://localhost:4008  # Placeholder, to be updated
      - key: JWT_SECRET_KEY
        value: mysecretkey123
      - key: FRONTEND_URL
        value: http://localhost:5173  # Placeholder, to be updated
      - key: CLOUDINARY_NAME
        value: djqw1de3s
      - key: CLOUDINARY_KEY
        value: 152654976184646
      - key: CLOUDINARY_SECRET
        value: IIB4wy5vb-BMnITnR583sd6MxLM
    region: virginia
