services:
  - type: web
    name: bamvswrld-client
    runtime: docker
    repo: https://github.com/TrioWolf/wrld_of_bam.git
    plan: standard
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: VITE_APP_ENV
        value: production
      - key: VITE_API_URL
        value: https://bamvswrld-server.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 630469049970-161iihf5mjh96rt6mj963asetm2cv665.apps.googleusercontent.com
      - key: VITE_CLOUDINARY_NAME
        value: djqw1de3s
      - key: VITE_BASE_URL
        value: https://bamvswrld-server.onrender.com
      - key: VITE_PORT
        value: 80
    region: virginia

  - type: web
    name: bamvswrld-server
    runtime: docker
    repo: https://github.com/TrioWol1f/wr1d_of_bam
    plan: standard
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4008
      - key: MONGO_URI
        value: mongodb+srv://tishd7:MihiaBFL68@fullstack.hkhucia.mongodb.net/?retryWrites=true&w=majority&appName=fullstack
      - key: GOOGLE_CLIENT_ID
        value: 630469049970-vlu6fe64h4dh1ljqdqlo538g33tqmh6t.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: SESSION_SECRET
        value: xg5St2ygd+mCIrMOjSomZ77kPpGK+yaDmVvvHf+z2aw4smGrmoKi1QyaPzRvaaXYJh4cN5uGf9oebpTzhmgt1w==
      - key: REDIRECT_URL
        value: https://bamvswrld-server.onrender.com/auth/google/callback
      - key: BASE_URL
        value: https://bamvswrld-server.onrender.com
      - key: API_URL
        value: https://bamvswrld-server.onrender.com
      - key: JWT_SECRET_KEY
        value: mysecretkey123
      - key: FRONTEND_URL
        value: https://bamvswrld.onrender.com
      - key: CLOUDINARY_NAME
        value: djqw1de3s
      - key: CLOUDINARY_KEY
        value: 152654976184646
      - key: CLOUDINARY_SECRET
        value: IIB4wy5vb-BMnITnR583sd6MxLM
    region: virginia
